plugins {
    id 'com.android.application'
}

android {
    namespace 'za.co.elevate.learning'
    compileSdk 34

    defaultConfig {
        applicationId 'za.co.elevate.learning'
        minSdk 23
        targetSdk 34
        versionCode 1
        versionName '1.0.0'

        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
        manifestPlaceholders = [
                hostName: 'ais-pre-6ockz5tdbznoghyafem3vj-389253933923.europe-west2.run.app',
                defaultUrl: 'https://ais-pre-6ockz5tdbznoghyafem3vj-389253933923.europe-west2.run.app',
                assetStatements: '[]'
        ]
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.androidbrowserhelper:androidbrowserhelper:2.5.0'
}
